sudo: required
language: python
services:
- docker
branches:
  only:
  - master
#before_install:
#- sudo docker build -t texlive docker
install:
- pip install ghp-import
script:
- make clean
- make build
- make github
env:
  global:
    secure: elkp31SWCh2LS6ORV86RRa/qYrpiiKRYejACFtIS6GC6FyYVQwtVmHpk+qXR+nMTt9GiTqQuOvuDlIer/yjlQ2FTjnibebWuUaI6PK44gfJ8IFriS0LaNDEnNwg1S13MoODGtG2aOA4Ej+YxMQgjrpUTTzDJskKZ0dGbUrSSYys/KYlDdv0iRubnzuwfrWqfCdbTndTdcj4pu3jpKXHZ1dnd43IaWt0IHI9SnO8xJn/FzumdDVzsKS0UBrgUIey+11axPoTLReyHBbfhwAi8djAeJmIK8+bSmR9zFK3yHp1ZBO0A8+6DacH+ZFue+q6+Cvp2v0k0bRu//ws36WOQqYoj3JRTQVgTkAMKIJBO0NaiKx1LPtq+4YJ9Cd/mcljXOzn56no7QZCeaygAMsS6HV5lL/B+2kse8VuYHes23W8BLHc1irCbeDr+bxxShEFOgMF3iuVT8fiO0ulbsfkkmOf9Q3Qp5BWa4fde9V73N+1w1ND3axy6duiJivA8marw6DsY8deAXWrTfF+IAT72xeMA9FrEm2QM1p8JO2ovPEjQGVyQ17zE3g0vhfJG6djGsYsfd+M4LSnWZ33K697+FcY36kczY0HuxhazOyQiQWJV02/HecNnH1RRQNkdu6Qar+MULzxOhnL3iK5rGwoG5fBsGkr1a0OaZ1lxlxGVUiw=
